# Generated by Django 5.2.8 on 2025-12-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_account',
            name='username',
            field=models.CharField(blank=True, unique=True),
        ),
    ]
