# Generated by Django 5.2.8 on 2025-12-01 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_user_account_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_account',
            name='username',
        ),
    ]
